#include<bits/stdc++.h>
using namespace std;
int main()
{
    char ch;
    while(scanf("%c",&ch)==1)
    {

        //a=strlen(ch);
        if(ch==' ')
        {
            cout<<" ";
        }
        if(ch=='1')
        {
            cout<<"`";
        }
        if(ch=='2')
        {
            cout<<"1";
        }
        if(ch=='3')
        {
            cout<<"2";
        }
        if(ch=='4')
        {
            cout<<"3";
        }
        if(ch=='5')
        {
            cout<<"4";
        }
        if(ch=='6')
        {
            cout<<"5";
        }
        if(ch=='7')
        {
            cout<<"6";
        }
        if(ch=='8')
        {
            cout<<"7";
        }
        if(ch=='9')
        {
            cout<<"8";
        }
        if(ch=='0')
        {
            cout<<"9";
        }
        if(ch=='-')
        {
            cout<<"0";
        }
        if(ch=='=')
        {
            cout<<"-";
        }
        if(ch=='W')
        {
            cout<<"Q";
        }
        if(ch=='E')
        {
            cout<<"W";
        }
        if(ch=='R')
        {
            cout<<"E";
        }
        if(ch=='T')
        {
            cout<<"R";
        }
        if(ch=='Y')
        {
            cout<<"T";
        }
        if(ch=='U')
        {
            cout<<"Y";
        }
        if(ch=='I')
        {
            cout<<"U";
        }
        if(ch=='O')
        {
            cout<<"I";
        }
        if(ch=='P')
        {
            cout<<"O";
        }
        if(ch=='[')
        {
            cout<<"P";
        }
        if(ch==']')
        {
            cout<<"[";
        }
        if(ch=='\\')
        {
            cout<<"]";
        }
        if(ch=='S')
        {
            cout<<"A";
        }
        if(ch=='D')
        {
            cout<<"S";
        }
        if(ch=='F')
        {
            cout<<"D";
        }
        if(ch=='G')
        {
            cout<<"F";
        }
        if(ch=='H')
        {
            cout<<"G";
        }
        if(ch=='J')
        {
            cout<<"H";
        }
        if(ch=='K')
        {
            cout<<"J";
        }
        if(ch=='L')
        {
            cout<<"K";
        }
        if(ch==';')
        {
            cout<<"L";
        }
        if(ch=='\'')
        {
            cout<<";";
        }
        if(ch=='X')
        {
            cout<<"Z";
        }
        if(ch=='C')
        {
            cout<<"X";
        }
        if(ch=='V')
        {
            cout<<"C";
        }
        if(ch=='B')
        {
            cout<<"V";
        }
        if(ch=='N')
        {
            cout<<"B";
        }
        if(ch=='M')
        {
            cout<<"N";
        }
        if(ch==',')
        {
            cout<<"M";
        }
        if(ch=='.')
        {
            cout<<",";
        }
        if(ch=='/')
        {
            cout<<".";
        }
        if(ch=='\n')
        {
            cout<<"\n";
        }


        //cout<<ch<<endl;
    }
    //cout<<endl;
}
